### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by walkureHHH** [notscuffed/repkg#11]
When I run it, it give me a exception,and can't run. How to solve it?
![9249d2b7ee59b0bf34ea0c8102b4176c0eab7669](https://user-images.githubusercontent.com/60261171/74644678-9c34f900-51b1-11ea-9ea2-7f025a93d991.jpg)

**Comment by notscuffed** [comment]
Make sure you have .NET Framework 4.7.2 installed

**Comment by walkureHHH** [comment]
> Make sure you have .NET Framework 4.7.2 installed

Thanks very much! I will try it.
