### ISSUE TITLE
NETFramework 4.7.2. required while u can´t rollback to it with the current Windows Update 

### ISSUE THREAD

**Issue by DankeRonneberg** [notscuffed/repkg#14]
So i tried using it and can´t find a way to get it to work.
The Windows Update History doesn´t let me uninstall the updates which changed the NETFramework Version and i can´t seem to install 4.7.2 since Windows detects a newer version and cancels the installation.
Is there a way to change / upgrade your tool to the Current version of NETFramework ?
Or maybe another workaround ?

**Comment by notscuffed** [comment]
You don't need 4.7.2 if you have newer one installed.

**Comment by DankeRonneberg** [comment]
i have a newer one installed and still get the error
The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found.
when starting .
( i did also install the developer pack because someone one Stack had his problem solved trough this but didn´t work for me)

Full Error below

Code:
 - MSB3644	

Description:
 - The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	

File:
 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	

Line:
- 1179

**Comment by notscuffed** [comment]
I've just tested on freshly installed Windows 10 Pro 2004, and Windows 10 Pro 1904 and it works just fine.

Which version of windows are you on?

If you want to compile it for .NET Framework 4.8 then change <TargetFramework>net472</TargetFramework> to <TargetFramework>net48</TargetFramework> inside .csproj's, or just let me know if you don't manage to do it yourself I'll compile it for you.

**Comment by DankeRonneberg** [comment]
Thanks a lot, that fixed my problem
