### ISSUE TITLE
Doesn't Open

### ISSUE THREAD

**Issue by Ciee29** [notscuffed/repkg#16]
I didn't have the .exe, but upon checking the other issues, I found the .exe, which probably means I'm missing the page where I'm supposed to find that. I've also checked other issues, and seen I'm supposed to open it with the console, which I assumed was Command Promt, but I've tried using that, Git CMD and Git Bash, as well as just opening the .exe file (Which I've tried placing in both the Desktop and the RePKG Source folder, neither of which make a difference). I'm not sure where I've gone wrong, but would appreciate any help you can give.

**Comment by notscuffed** [comment]
I've recorded a video showing me using it.

https://streamable.com/k44f87

Let me know if you managed to follow it.

**Comment by Ciee29** [comment]
That was absolutely perfect. Thank you, I really appreciate that.
