### ISSUE TITLE
How to convert it to video?

### ISSUE THREAD

**Issue by JoeyBling** [notscuffed/repkg#19]
How to convert it to video?
like this one
> https://steamcommunity.com/sharedfiles/filedetails/?id=1664684538&searchtext=

**Comment by notscuffed** [comment]
I took a look at the steam page and it looks like a shader. Converting shader to video is out of scope of this program.

You'll either have to record your screen or write a program that would render it to video.

**Comment by JoeyBling** [comment]
thx
