### ISSUE TITLE
'RePKG' debug profile does not exist

### ISSUE THREAD

**Issue by Scuachu** [notscuffed/repkg#21]
Apologies if I'm being dumb but I'm running into an issue that I can't find the solution to.
![image](https://user-images.githubusercontent.com/78068044/105951049-92a35900-60c3-11eb-92da-03b7fb12a60e.png)

**Comment by notscuffed** [comment]
I don't use visual studio for C# programming, but I did test the project in it just now and it debugs just fine for me.

Something must be wrong with ur environment.
