### ISSUE TITLE
Animated wallpapers storing as static JPEG files

### ISSUE THREAD

**Issue by GMPranav** [notscuffed/repkg#25]
I downloaded some animated wallpaper projects but when I extract them, they just get stored as a static JPEG file. I was expecting to see a GIF file instead. There are some also some subfolders with "effects", "masks" that contain some PNG files that seemingly are supposed to form the animated elements but I have no idea how to put together those files. Does repkg natively support doing this with a setting or am I out of options?

Here is the project I am trying to extract btw if it helps - https://steamcommunity.com/sharedfiles/filedetails/?id=2426441418

**Comment by notscuffed** [comment]
You expected wrong then, this wallpaper is animated using shaders. There are no gifs inside that pkg nor does the tool support rendering the wallpaper to gif.
