### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by websecnl** [notscuffed/repkg#26]
Could you add a feature which converts the output back to .tex ? (Recompiling Feature)

**Comment by websecnl** [comment]
Ah thanks I see.

I did this:

resourcecompiler.exe -tex -i "C:\Users\Name\Desktop\ExtractTEX\output\THS.png" -o "C:\Users\Name\Desktop\ExtractTEX\output\THS.tex"

However this does not include the json .tex-json file , using what command can I include it in my .tex file?

Could you please help a bit with this, would appreciate it.

**Comment by notscuffed** [comment]
Create C:\Users\Name\Desktop\ExtractTEX\output\THS.tex-json beside the input image file.
