### ISSUE TITLE
couldn't get it to decompress a .tex file

### ISSUE THREAD

**Issue by cramer28** [notscuffed/repkg#3]
i tried with the examples(changing the dir ofc) but couldn't make it work, ex:

>D:\Downloads\Wallpaper.Engine.Pkg.To.Zip>repkg extract -t -d D:\Downloads\Wallpaper.Engine.Pkg.To.Zip\fondo\materials
> * Decompiling: D:\Downloads\Wallpaper.Engine.Pkg.To.Zip\fondo\materials\v2-85a6dd9256b0167c08a83688c4e54c0a_r.tex
> Format: ARGB8888
> _unkInt_1: 2
> _unkInt_2: 4281805824
> _unkIntCont_0: 1
> ImageFormat: FIF_UNKNOWN
> Failed to decompile
> System.IO.DirectoryNotFoundException: No se puede encontrar una parte de la ruta de acceso 'D:\Downloads\Wallpaper.Engine.Pkg.To.Zip\output\v2-85a6dd9256b0167c08a83688c4e54c0a_r.png'.
>    en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    en System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
>    en System.IO.File.WriteAllBytes(String path, Byte[] bytes)
>    en RePKG.Texture.Tex.DecompileAndSave(String path, Boolean overwrite)
>    en RePKG.Command.Extract.ExtractTexDirectory(DirectoryInfo directoryInfo)
> Done

used the '-d' tag in that last one hoping it would help solving this.
maybe im forgetting something

**Comment by notscuffed** [comment]
There's a bug that causes it to crash if there's no output folder created.. I'll fix the bug now.

**Comment by notscuffed** [comment]
Uploaded fixed release, if you encounter any issues let me know.
