### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by MCHaderlie** [notscuffed/repkg#37]
I am running the following code, but no output is being created. I've tried it with the precomplied version you provided and one that I complied myself. Tried it in admin and normal powershell. Also tried all of the examples that you provided in the readme

PS C:\Users\mchad\Desktop\build> .\repkg.exe extract -e tex -s -o "C:\Users\mchad\Desktop\scene (2)\Unpacked" "C:\Users\mchad\Desktop\scene (2)"

**Comment by lanpesk** [comment]
the input path should be the pervious level folder. 
such as:
```
rootpath
    └─scene
        ├─scene.pkg
        └─other file
```
the command is:
```
./repkg extract -o ./output rootpath
```
