### ISSUE TITLE
Support for TEXB0001

### ISSUE THREAD

**Issue by kvdrrrrr** [notscuffed/repkg#4]
Apparently, `TexLoader::LoadTex` does not support loading "version 1" texture containers. 

[Example hex-view of version 1 texture](https://imgur.com/a/etq7CRM)

**Comment by notscuffed** [comment]
Could you upload the .pkg file containing this .tex somewhere and send it to me? Or the name so I can find it in workshop.

**Comment by kvdrrrrr** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=833227004

background.tex

**Comment by notscuffed** [comment]
I've added the support for it
