### ISSUE TITLE
Compiled Release Link

### ISSUE THREAD

**Issue by dtomper** [notscuffed/repkg#44]
I don't know why the owner couldn't just put a release on this repo, I had to download the entirety of Visual Studio to compile this as a result of that... But anyway, I uploaded it on MediaFire so you guys don't have to go through the same shit I went through :)

**Comment by Sidiusz** [comment]
Nice! Link, please?

**Comment by Sidiusz** [comment]
Yeah but https://github.com/notscuffed/repkg/releases
