### ISSUE TITLE
Error: System.NotImplementedException: Format: "8" (8)

### ISSUE THREAD

**Issue by Vivi029** [notscuffed/repkg#7]
Hello,

I was looking for an extractor for the tex files in wallpaper-engine and I found this software.
I tried using it to extracte the .tex files contained by default in wallpaper engine and I ran into this error by running this command:
RePKG.exe extract -t F:\app\Wallpaper-engine-extrator\fileToExtract

And this is the output:

* Decompiling: F:\app\Wallpaper-engine-extrator\fileToExtract\fog1.tex
Failed to decompile
System.NotImplementedException: Format: "9" (9)
   à RePKG.Texture.Tex.Decompile()
   à RePKG.Texture.Tex.DecompileAndSave(String path, Boolean overwrite)
   à RePKG.Command.Extract.ExtractTexDirectory(DirectoryInfo directoryInfo)
* Decompiling: F:\app\Wallpaper-engine-extrator\fileToExtract\fog2.tex
Failed to decompile
System.NotImplementedException: Format: "8" (8)
   à RePKG.Texture.Tex.Decompile()
   à RePKG.Texture.Tex.DecompileAndSave(String path, Boolean overwrite)
   à RePKG.Command.Extract.ExtractTexDirectory(DirectoryInfo directoryInfo)
* Decompiling: F:\app\Wallpaper-engine-extrator\fileToExtract\fog3.tex
Failed to decompile
System.NotImplementedException: Format: "8" (8)
   à RePKG.Texture.Tex.Decompile()
   à RePKG.Texture.Tex.DecompileAndSave(String path, Boolean overwrite)
   à RePKG.Command.Extract.ExtractTexDirectory(DirectoryInfo directoryInfo)
Done

Does this error has to do with my command or with the software ?

Here are the files in the extract directory:

![image](https://user-images.githubusercontent.com/43375475/64323340-990fcd00-cfc4-11e9-8f0f-7ed2db25c7ef.png)

Thanks for your answer and nice work.

**Comment by notscuffed** [comment]
Hi, could you send me the .tex files/link to steam workshop of wallpaper that you are trying to extract?

**Comment by Vivi029** [comment]
Well there is no workshop page, they are directly in the wallpaper engine files.

I think they are located in the material/<particle or effect>/fog I will look it up once i'm on my pc

**Comment by notscuffed** [comment]
I found them, I'll see if I can add support for this type of tex files.

**Comment by Vivi029** [comment]
Great I wish you good luck !!

**Comment by notscuffed** [comment]
I've added support for those types.

**Comment by Vivi029** [comment]
It works just as intended,
Very good work thank you 👍
