### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by wavevan** [notscuffed/repkg#8]
Not familiar with your programming language and IDE, can you provide a compiled executable file? Thank you very much.

**Comment by notscuffed** [comment]
Hello, there's releases button that you can click that will take you to download section with binaries. Screenshot: [https://i.imgur.com/829VG2B.png](https://i.imgur.com/829VG2B.png)

But here's direct link just in case: [https://github.com/notscuffed/repkg/releases/download/v0.1.7-alpha/RePKG.exe](https://github.com/notscuffed/repkg/releases/download/v0.1.7-alpha/RePKG.exe)

**Comment by wavevan** [comment]
Thank you very much for your help.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notscuffed"<notifications@github.com&gt;; 
发送时间: 2020年1月5日(星期天) 凌晨3:38
收件人: "notscuffed/repkg"<repkg@noreply.github.com&gt;; 
抄送: "wave"<948277346@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [notscuffed/repkg] I need help (#8)




Hello, there's releases button that you can click that will take you to download section with binaries. Screenshot: https://i.imgur.com/829VG2B.png
 
But here's direct link just in case: https://github.com/notscuffed/repkg/releases/download/v0.1.7-alpha/RePKG.exe
